# Generated by Django 5.2.3 on 2025-07-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodel',
            name='type',
            field=models.CharField(choices=[('mcq', 'multiple choice question'), ('open', 'open question'), ('true_false', 'true or false question')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
