# Generated by Django 5.2.4 on 2025-07-14 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_questionmodel_type'),
        ('professors', '0002_alter_professorprofilemodel_university_and_more'),
        ('university', '0002_alter_facultymodel_university_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentattachmentsmodel',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='assignments.assingmentmodel'),
        ),
        migrations.AlterField(
            model_name='assignmentsgroupmodel',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='assignments.assingmentmodel'),
        ),
        migrations.AlterField(
            model_name='assignmentsgroupmodel',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_groups', to='university.groupmodel'),
        ),
        migrations.AlterField(
            model_name='assingmentmodel',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='professors.professorprofilemodel'),
        ),
        migrations.AlterField(
            model_name='assingmentmodel',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='university.subjectmodel'),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assignments.assingmentmodel'),
        ),
    ]
