# Generated by Django 5.2.4 on 2025-07-18 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_alter_assignmentattachmentsmodel_assignment_and_more'),
        ('professors', '0004_alter_professorssubjectmodel_professor'),
        ('students', '0012_alter_cheatingevidencemodel_session'),
        ('university', '0005_alter_universitymodel_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssingmentModel',
            new_name='AssignmentModel',
        ),
    ]
