# Generated by Django 5.2.4 on 2025-07-20 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_rename_assingmentmodel_assignmentmodel'),
        ('university', '0005_alter_universitymodel_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignmentsgroupmodel',
            unique_together={('assignment', 'group')},
        ),
    ]
