# Generated by Django 5.2.3 on 2025-07-01 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professors', '0001_initial'),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='professors.professorprofilemodel')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.universitymodel')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('intro_video', models.FileField(blank=True, null=True, upload_to='uploads/course_section/video/%Y/%m/%d/')),
                ('intro_image', models.ImageField(blank=True, null=True, upload_to='uploads/course_section/video/%Y/%m/%d/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursemodel')),
            ],
        ),
        migrations.CreateModel(
            name='CourseLessonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('video', models.FileField(blank=True, null=True, upload_to='uploads/course_lesson/video/%Y/%m/%d/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/course_lesson/image/%Y/%m/%d/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursesectionmodel')),
            ],
        ),
    ]
