# Generated by Django 5.2.3 on 2025-07-09 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='intro_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/course/%Y/%m/%d/'),
        ),
    ]
