# Generated by Django 5.2.4 on 2025-07-10 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_coursemodel_intro_image'),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodel',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='coursemodel',
            name='university',
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.subjectmodel'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CourseAttachmentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_file', models.FileField(upload_to='')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursemodel')),
            ],
        ),
    ]
