# Generated by Django 5.2.4 on 2025-07-14 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_coursemodel_professor_and_more'),
        ('university', '0002_alter_facultymodel_university_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseattachmentsmodel',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_attachments', to='course.coursemodel'),
        ),
        migrations.AlterField(
            model_name='courselessonmodel',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='course.coursesectionmodel'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='university.subjectmodel'),
        ),
        migrations.AlterField(
            model_name='coursesectionmodel',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='course.coursemodel'),
        ),
    ]
