# Generated by Django 5.2.3 on 2025-07-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentcoursemodel_studencourseprogressmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsessionmodel',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentsessionmodel',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
