# Generated by Django 5.2.3 on 2025-07-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_studentsessionmodel_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheatingevidencemodel',
            name='type',
            field=models.CharField(choices=[('device', 'device'), ('multiple_people', 'multiple_people'), ('audio', 'audio'), ('ai', 'ai'), ('tab_switch', 'Tab switch')], max_length=20),
        ),
    ]
