# Generated by Django 5.2.3 on 2025-07-09 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0001_initial'),
        ('students', '0004_alter_cheatingevidencemodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttimetablesubjectmodel',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professors.professorprofilemodel'),
        ),
    ]
