# Generated by Django 5.2.4 on 2025-07-14 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_alter_assignmentattachmentsmodel_assignment_and_more'),
        ('course', '0004_alter_courseattachmentsmodel_course_and_more'),
        ('students', '0005_alter_studenttimetablesubjectmodel_professor'),
        ('university', '0002_alter_facultymodel_university_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studencourseprogressmodel',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progresses', to='course.courselessonmodel'),
        ),
        migrations.AlterField(
            model_name='studencourseprogressmodel',
            name='student_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='students.studentcoursemodel'),
        ),
        migrations.AlterField(
            model_name='studentanswermodel',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='assignments.questionchoicemodel'),
        ),
        migrations.AlterField(
            model_name='studentanswermodel',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='assignments.questionmodel'),
        ),
        migrations.AlterField(
            model_name='studentanswermodel',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='students.studentsessionmodel'),
        ),
        migrations.AlterField(
            model_name='studentcoursemodel',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_courses', to='course.coursemodel'),
        ),
        migrations.AlterField(
            model_name='studentcoursemodel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='students.studentprofilemodel'),
        ),
        migrations.AlterField(
            model_name='studentprofilemodel',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_profiles', to='university.universitymodel'),
        ),
        migrations.AlterField(
            model_name='studentprofilemodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentsessionmodel',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_sessions', to='assignments.assingmentmodel'),
        ),
        migrations.AlterField(
            model_name='studentsessionmodel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='students.studentprofilemodel'),
        ),
        migrations.AlterField(
            model_name='studentsgroupmodel',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='university.groupmodel'),
        ),
        migrations.AlterField(
            model_name='studentsgroupmodel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='students.studentprofilemodel'),
        ),
        migrations.AlterField(
            model_name='studenttimetablemodel',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_timetables', to='university.groupmodel'),
        ),
    ]
