# Generated by Django 5.2.4 on 2025-07-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_courseattachmentsmodel_course_and_more'),
        ('students', '0006_alter_studencourseprogressmodel_lesson_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudenCourseProgressModel',
            new_name='StudentCourseProgressModel',
        ),
        migrations.RenameField(
            model_name='studentprofilemodel',
            old_name='student_id',
            new_name='student_id_number',
        ),
        migrations.AddField(
            model_name='studentprofilemodel',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofilemodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='studentprofilemodel',
            name='first_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofilemodel',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentprofilemodel',
            name='gender_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentprofilemodel',
            name='gender_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentprofilemodel',
            name='image_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofilemodel',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentprofilemodel',
            name='passport_pin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentprofilemodel',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentprofilemodel',
            name='second_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofilemodel',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofilemodel',
            name='third_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
