# Generated by Django 5.2.4 on 2025-07-15 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_rename_studencourseprogressmodel_studentcourseprogressmodel_and_more'),
        ('university', '0004_remove_subjectmodel_description_subjectmodel_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='students.studentprofilemodel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='university.subjectmodel')),
            ],
        ),
    ]
