# Generated by Django 5.2.4 on 2025-07-16 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_studentsubjectmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttimetablesubjectmodel',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='students.studenttimetablemodel'),
        ),
    ]
