# Generated by Django 5.2.4 on 2025-07-16 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0004_alter_professorssubjectmodel_professor'),
        ('students', '0009_alter_studenttimetablesubjectmodel_timetable'),
        ('university', '0005_alter_universitymodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttimetablesubjectmodel',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_subjects', to='professors.professorprofilemodel'),
        ),
        migrations.AlterField(
            model_name='studenttimetablesubjectmodel',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='university.subjectmodel'),
        ),
    ]
