# Generated by Django 5.2.4 on 2025-07-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_studenttimetablesubjectmodel_professor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsessionmodel',
            name='cheating_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentsessionmodel',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
