# Generated by Django 5.2.4 on 2025-07-17 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_studentsessionmodel_cheating_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheatingevidencemodel',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheating_evidence', to='students.studentsessionmodel'),
        ),
    ]
