# Generated by Django 5.2.4 on 2025-07-20 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_alter_assignmentsgroupmodel_unique_together'),
        ('students', '0012_alter_cheatingevidencemodel_session'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentanswermodel',
            unique_together={('session', 'question')},
        ),
    ]
