# Generated by Django 5.2.4 on 2025-07-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_alter_studentanswermodel_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcoursemodel',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentcoursemodel',
            name='is_completed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
