# Generated by Django 5.2.4 on 2025-07-25 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_courseattachmentsmodel_course_and_more'),
        ('students', '0014_alter_studentcoursemodel_end_time_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentcourseprogressmodel',
            unique_together={('student_course', 'lesson')},
        ),
    ]
