# Generated by Django 5.2.4 on 2025-07-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_alter_studentcourseprogressmodel_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsessionmodel',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
