# Generated by Django 5.2.4 on 2025-07-14 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultymodel',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='university.universitymodel'),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='university.departmentmodel'),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='university.universitymodel'),
        ),
        migrations.AlterField(
            model_name='subjectmodel',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='university.departmentmodel'),
        ),
        migrations.AlterField(
            model_name='subjectmodel',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='university.universitymodel'),
        ),
        migrations.AlterField(
            model_name='universitymodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universitymodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='universitymodel',
            name='latitude',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universitymodel',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='universitymodel',
            name='longtitude',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universitymodel',
            name='number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='universitymodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='universities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='universitymodel',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
