# Generated by Django 5.2.4 on 2025-07-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_alter_facultymodel_university_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentmodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='facultymodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='groupmodel',
            name='number',
        ),
        migrations.AddField(
            model_name='departmentmodel',
            name='code',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facultymodel',
            name='code',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupmodel',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
