# Generated by Django 5.2.4 on 2025-07-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_remove_departmentmodel_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectmodel',
            name='description',
        ),
        migrations.AddField(
            model_name='subjectmodel',
            name='code',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
