# Generated by Django 5.2.4 on 2025-07-14 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0002_alter_facultymodel_university_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityUrlsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('api_url', models.URLField(max_length=500)),
                ('student_url', models.URLField(max_length=500)),
                ('employee_url', models.URLField(max_length=500)),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.universitymodel')),
            ],
        ),
    ]
