# Generated by Django 5.2.4 on 2025-07-14 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0001_initial'),
        ('university', '0002_alter_facultymodel_university_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='professorprofilemodel',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_profiles', to='university.universitymodel'),
        ),
        migrations.AlterField(
            model_name='professorprofilemodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='professorssubjectmodel',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='professors.professorprofilemodel'),
        ),
        migrations.AlterField(
            model_name='professorssubjectmodel',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professors', to='university.subjectmodel'),
        ),
    ]
