# Generated by Django 5.2.4 on 2025-07-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0002_alter_professorprofilemodel_university_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professorprofilemodel',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
