# Generated by Django 5.2.4 on 2025-07-16 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0003_professorprofilemodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professorssubjectmodel',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_subjects', to='professors.professorprofilemodel'),
        ),
    ]
